### ISSUE TITLE
Day 2: returning tuples

### ISSUE THREAD

**Issue by bas-ie** [BurntSushi/advent-of-code#4]
Hello again! I finished this when I had time, then refactored after reviewing your solution. I saw your comment on Twitter saying to ask questions, so I'm piling on :smile:

I managed to make my first effort a little more efficient, but I had questions which I guess are mostly about idiom. The task seems to lend itself to one function returning a tuple (indicating positives for sequences of two chars and sequences of three chars). So I went for this:

```rust
use std::collections::HashSet;

pub fn count_dups (id: &str) -> (u32, u32) {
    let (mut twos, mut threes) = (false, false);
    let mut unique_chars = HashSet::new();

    for c in id.chars() {
        let unique = unique_chars.insert(c);
        if !unique {
            let count = id.matches(c).count();
            if count == 2 {
                twos = true;
            }
            if count == 3 {
                threes = true;
            }
        }
    }
    (twos as u32, threes as u32)
}

#[aoc(day2, part1)]
pub fn find_checksum (ids: &str) -> u32 {
    let (twos, threes) = ids
        .lines()
        .fold((0, 0), |counts, id| {
            let dups = count_dups(id);
            (counts.0 + dups.0, counts.1 + dups.1)
        });
    twos * threes        
}
```
This clocks in at about 350 µs without the file read (yours is 50-ish). TBH I should probably stop playing bench golf and focus on readability, but it's addictive. Anyway, is returning the tuple a reasonably idiomatic approach? And is there a cleaner way of obtaining the totals? The fold as written seems a little untidy.

**Comment by BurntSushi** [comment]
Personally, I would probably use a named type for this:

```rust
struct Counts {
    twos: u64,
    threes: u64,
}
```

and return that instead. The general problem with tuples is that they are _anonymous_. In other words, their components are unnamed, so it can be difficult to track which part of a tuple means what. I do use tuples from time to time, but generally only if their component types make the meaning of each component really obvious (e.g., `(Foo, Bar)`), or if a tuple is a somewhat natural representation (like a coordinate or a vector). But even then, I don't always choose a tuple.

In terms of the fold, I almost never use folds. I prefer writing out the loop. With that said, I think your fold is fine.

In terms of performance, I am not benchmarking my answers. It would take me too long if I did that, and I wouldn't be able to complete the puzzles. On top of that, the input sets are so constrained that benchmarking isn't really meaningful unless you either expand the input sizes dramatically or set some arbitrary restrictions on the properties of the input data. Usually, performance is very heavily coupled with the *assumptions* you can make about input. So far, for example, all input has been ASCII and otherwise well formed. If you assume that's true in general, then you can avoid certain types of processing. And of course, this is only the most shallow of possible assumptions one can make. For example, in one of the previous problems that involved dealing with an infinite grid, the solution is markedly simpler if you can assume a somewhat small upper bound on the size of the grid, even though the problem statement claims it is infinite. Is that assumption fair game in benchmarking? Or do you really need to treat it as infinite?

**Comment by bas-ie** [comment]
Thanks so much for taking the time to respond, that all makes a lot of sense. I'm part-way through using a named type for day 3, so I'm slowly getting to grips with how that all works. By the end of the advent I should only be about 20 days behind!
